title: Salesforce Style Guide
description: A style guide with guidelines for building a clean Salesforce org
             that's easy on the eyes and simple to maintain
show_downloads: false
google_analytics:
theme: jekyll-theme-leap-day